FROM grafana/grafana:10.4.0@sha256:f9811e4e687ffecf1a43adb9b64096c50bc0d7a782f8608530f478b6542de7d5

COPY platform/docker/grafana/grafana.ini /etc/grafana/grafana.ini
COPY platform/docker/grafana/provisioning/datasources/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY platform/docker/grafana/provisioning/dashboards/dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY platform/docker/grafana/provisioning/dashboards/aea_unified_dashboard.json /etc/grafana/provisioning/dashboards/aea_unified_dashboard.json
COPY platform/docker/grafana/provisioning/dashboards/aea_executive_dashboard.json /etc/grafana/provisioning/dashboards/aea_executive_dashboard.json

EXPOSE 3000
