events {}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  limit_req_zone $binary_remote_addr zone=edge:10m rate=20r/s;
  server_tokens off;
  resolver __RESOLVER__ valid=10s ipv6=off;
  server {
    listen 8080;
    root /usr/share/nginx/html;
    client_max_body_size 64k;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;
    add_header Content-Security-Policy "default-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always;
    location = / {
      try_files /index.html =404;
    }
    location = /florist {
      try_files /florist.html =404;
    }
    location /assets/ {
      try_files $uri =404;
    }
    location /api/ {
      limit_req zone=edge burst=40 nodelay;
      set $bff_upstream __BFF_UPSTREAM__;
      proxy_set_header X-Internal-Identity "";
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $bff_upstream;
      proxy_buffering off;
    }
    location = /healthz {
      limit_req zone=edge burst=40 nodelay;
      set $bff_upstream __BFF_UPSTREAM__;
      proxy_set_header X-Internal-Identity "";
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $bff_upstream;
      proxy_buffering off;
    }
    location /webhooks/ {
      limit_req zone=edge burst=40 nodelay;
      set $agent_upstream __AGENT_UPSTREAM__;
      proxy_set_header X-Internal-Identity "";
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $agent_upstream;
      proxy_buffering off;
    }
    location /cloud/ {
      limit_req zone=edge burst=40 nodelay;
      set $agent_upstream __AGENT_UPSTREAM__;
      proxy_set_header X-Internal-Identity "";
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $agent_upstream;
      proxy_buffering off;
    }
<<<<<<< Updated upstream
=======
    location = /metrics {
      limit_req zone=edge burst=40 nodelay;
      set $agent_upstream __AGENT_UPSTREAM__;
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $agent_upstream;
      proxy_buffering off;
    }
    location /grafana/ {
      limit_req zone=edge burst=40 nodelay;
      set $grafana_upstream http://grafana.aea-pilot.internal:3000;
      proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      proxy_set_header Host $host;
      proxy_pass $grafana_upstream;
      proxy_buffering off;
    }
>>>>>>> Stashed changes
  }
}

