#!/usr/bin/env python3
"""Compile committed platform/edge Python lock files from human-authored inputs (#329)."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUTS = (
    ROOT / "platform" / "requirements.txt",
    ROOT / "edge" / "requirements.txt",
)
LOCK_NAME = "requirements.lock"
HEADER = "# Generated by scripts/compile_python_locks.py. Do not edit."
INSTALLER_PACKAGES = frozenset({"pip", "setuptools", "wheel"})
# Extra packages implied by a human-authored extra. The extra package is
# constrained to the same version as the parent when present in the lock.
EXTRA_LOCK_NAMES = {
    "psycopg": ("psycopg-binary",),
}


def canonicalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def lock_path_for(requirements: Path) -> Path:
    return requirements.with_name(LOCK_NAME)


def parse_version(version: str) -> tuple[int, ...]:
    parts: list[int] = []
    for token in version.split("."):
        match = re.match(r"(\d+)", token)
        if not match:
            break
        parts.append(int(match.group(1)))
    if not parts:
        raise ValueError(f"unparseable version: {version}")
    return tuple(parts)


def version_cmp(left: tuple[int, ...], right: tuple[int, ...]) -> int:
    width = max(len(left), len(right))
    left_p = left + (0,) * (width - len(left))
    right_p = right + (0,) * (width - len(right))
    return (left_p > right_p) - (left_p < right_p)


def specifier_matches(version: str, specifier: str) -> bool:
    parsed = parse_version(version)
    for clause in specifier.split(","):
        clause = clause.strip()
        match = re.match(r"^(<=|>=|==|!=|<|>)(.+)$", clause)
        if not match:
            return False
        op, raw = match.group(1), match.group(2).strip()
        other = parse_version(raw)
        cmp = version_cmp(parsed, other)
        if op == "==" and cmp != 0:
            return False
        if op == "!=" and cmp == 0:
            return False
        if op == ">=" and cmp < 0:
            return False
        if op == "<=" and cmp > 0:
            return False
        if op == ">" and cmp <= 0:
            return False
        if op == "<" and cmp >= 0:
            return False
    return True


def parse_requirement_line(line: str) -> tuple[str, str] | None:
    stripped = line.split("#", 1)[0].strip()
    if not stripped:
        return None
    match = re.match(r"^([A-Za-z0-9_.-]+)(?:\[[^\]]+\])?\s*(.*)$", stripped)
    if not match:
        raise ValueError(f"unparseable requirement: {line}")
    name = canonicalize_name(match.group(1))
    spec = match.group(2).strip() or "==0"
    return name, spec


def parse_requirements(requirements: Path) -> list[tuple[str, str]]:
    parsed: list[tuple[str, str]] = []
    for line in requirements.read_text(encoding="utf-8").splitlines():
        item = parse_requirement_line(line)
        if item:
            parsed.append(item)
    if not parsed:
        raise ValueError(f"no requirements in {requirements}")
    return parsed


def parse_lock(lock: Path) -> list[tuple[str, str]]:
    pins: list[tuple[str, str]] = []
    for line in lock.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        match = re.match(r"^([A-Za-z0-9.-]+)==(.+)$", line.strip())
        if not match:
            raise ValueError(f"unparseable lock line in {lock}: {line}")
        pins.append((canonicalize_name(match.group(1)), match.group(2).strip()))
    return pins


def render_lock(requirements: Path, pins: list[tuple[str, str]]) -> str:
    rel = requirements.relative_to(ROOT).as_posix() if requirements.is_relative_to(ROOT) else requirements.name
    lines = [HEADER, f"# Input: {rel}", ""]
    lines.extend(f"{name}=={version}" for name, version in pins)
    return "\n".join(lines) + "\n"


def pin_map(pins: list[tuple[str, str]]) -> dict[str, str]:
    return {name: version for name, version in pins}


def input_errors(requirements: Path, pins: list[tuple[str, str]]) -> list[str]:
    errors: list[str] = []
    locked = pin_map(pins)
    rel = lock_path_for(requirements).name
    for name, spec in parse_requirements(requirements):
        if name not in locked:
            errors.append(f"{rel} missing pin for input {name}")
            continue
        if not specifier_matches(locked[name], spec):
            errors.append(f"{rel} pin {name}=={locked[name]} does not satisfy {spec}")
        for extra in EXTRA_LOCK_NAMES.get(name, ()):
            if extra not in locked:
                errors.append(f"{rel} missing extra pin {extra} for {name}")
            elif locked[extra] != locked[name]:
                errors.append(f"{rel} extra pin {extra}=={locked[extra]} must match {name}=={locked[name]}")
    return errors


def resolve_pins(requirements: Path) -> list[tuple[str, str]]:
    if not requirements.is_file():
        raise FileNotFoundError(f"missing input: {requirements}")
    with tempfile.TemporaryDirectory(prefix="aea-python-lock-") as tmp:
        report_path = Path(tmp) / "report.json"
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--disable-pip-version-check",
                "--report",
                str(report_path),
                "-r",
                str(requirements),
            ],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "pip resolve failed for "
                f"{requirements}:\n{result.stdout}\n{result.stderr}"
            )
        report = json.loads(report_path.read_text(encoding="utf-8"))
    pins: dict[str, str] = {}
    for item in report.get("install", []):
        metadata = item.get("metadata") or {}
        name = canonicalize_name(str(metadata.get("name") or ""))
        version = str(metadata.get("version") or "").strip()
        if not name or not version or name in INSTALLER_PACKAGES:
            continue
        pins[name] = version
    if not pins:
        raise RuntimeError(f"pip report produced no pins for {requirements}")
    return sorted(pins.items())


def compile_lock(requirements: Path) -> str:
    return render_lock(requirements, resolve_pins(requirements))


def write_locks(inputs: tuple[Path, ...] = INPUTS) -> list[Path]:
    written: list[Path] = []
    for requirements in inputs:
        lock = lock_path_for(requirements)
        lock.write_text(compile_lock(requirements), encoding="utf-8")
        written.append(lock)
    return written


def check_locks(inputs: tuple[Path, ...] = INPUTS) -> list[str]:
    """Unchanged regeneration of committed pins must have no diff."""
    errors: list[str] = []
    for requirements in inputs:
        lock = lock_path_for(requirements)
        rel = lock.name if not lock.is_relative_to(ROOT) else lock.relative_to(ROOT).as_posix()
        if not requirements.is_file():
            errors.append(f"missing input: {requirements}")
            continue
        if not lock.is_file():
            errors.append(f"missing lock: {rel}")
            continue
        try:
            pins = parse_lock(lock)
        except ValueError as exc:
            errors.append(str(exc))
            continue
        expected = render_lock(requirements, pins)
        actual = lock.read_text(encoding="utf-8")
        if actual != expected:
            errors.append(f"lock drifted: {rel} (regenerate with scripts/compile_python_locks.py)")
        errors.extend(input_errors(requirements, pins))
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--upgrade",
        action="store_true",
        help="Re-resolve from the current index and rewrite lock files.",
    )
    args = parser.parse_args(argv)
    try:
        if args.upgrade and args.check:
            print("FAIL: use --check or --upgrade, not both", file=sys.stderr)
            return 2
        if args.check:
            errors = check_locks()
            if errors:
                print("FAIL: Python lock regeneration has a diff", file=sys.stderr)
                for error in errors:
                    print(f"  - {error}", file=sys.stderr)
                return 1
            print("ok: platform and edge Python locks match unchanged regeneration")
            return 0
        written = write_locks()
        for lock in written:
            print(f"wrote {lock.relative_to(ROOT).as_posix()}")
        return 0
    except (FileNotFoundError, RuntimeError, OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
