"""Session Memory Extractor CLI.

Extracts session building process, git commits, architectural decisions, and lessons learned
into a draft Second Brain Obsidian memory note under research/random-thoughts/.

Usage:
  python scripts/extract_session_memory.py [--title "Session Title"]
"""

import sys
import json
import argparse
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RANDOM_THOUGHTS = ROOT / "research" / "random-thoughts"


def get_git_commits(limit: int = 5) -> list[str]:
    try:
        res = subprocess.run(
            ["git", "log", f"-n{limit}", "--oneline"],
            cwd=ROOT, capture_output=True, text=True, check=True
        )
        return [line.strip() for line in res.stdout.strip().split("\n") if line.strip()]
    except Exception:
        return []


def extract_session_memory(title: str) -> Path:
    RANDOM_THOUGHTS.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    clean_title = title.lower().replace(" ", "-").replace("/", "-")
    filename = f"{today}-{clean_title}.md"
    target_path = RANDOM_THOUGHTS / filename

    commits = get_git_commits(5)
    commits_md = "\n".join([f"- `{c}`" for c in commits]) if commits else "- No recent commits"

    content = f"""# Project Memory Log: {title}

> **Tags**: #aea #second-brain #session-memory #building-process #history
> **Captured Date**: {today}
> **Target Vault Location**: `research/random-thoughts/{filename}`

---

## Executive Summary

Draft memory log automatically generated by `scripts/extract_session_memory.py`.

---

## 1. Recent Git Commit History

{commits_md}

---

## 2. Key Decisions & Technical Trade-offs

* **Decision 1**: Document session architectural decisions here.
* **Trade-off**: Record trade-offs and alternative approaches evaluated.

---

## 3. Lessons Learned & Post-Mortem Findings

* **Lesson 1**: Record bug root causes and engineering solutions.
* **Cross-Link**: [[ADR-001]], [[ADR-016]], [[2026-08-21-aea-strategic-architecture-study]]
"""

    target_path.write_text(content, encoding="utf-8")
    print(f"ok: created draft session memory log at {target_path.relative_to(ROOT)}")
    return target_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract session memory into Second Brain node")
    parser.add_argument("--title", default="session-memory-log", help="Title for the session memory note")
    args = parser.parse_args()
    extract_session_memory(args.title)
