"""LOAD-004: Post-Load Test Data Purge Engine (NFR-017 / M13).

Purges test sessions prefixed with `session_loadtest_*` or generated by Locust load runs
from the PostgreSQL database after a load testing run completes.
"""

import os
import sys
import psycopg

DSN = os.environ.get(
    "AEA_POSTGRES_DSN",
    "postgresql://aea_migration:local-migration-only@localhost:5432/adaptive_experience"
)

def purge_load_test_data(dsn: str) -> dict:
    """Purge temporary load test records from PostgreSQL."""
    counts = {}
    with psycopg.connect(dsn, autocommit=True) as conn:
        with conn.cursor() as cur:
            # 1. Purge outbox messages
            cur.execute("DELETE FROM orchestration.outbox_message WHERE session_id LIKE 'session_loadtest_%'")
            counts["outbox_messages"] = cur.rowcount

            # 2. Purge customer orders
            cur.execute("DELETE FROM orchestration.customer_order WHERE session_id LIKE 'session_loadtest_%'")
            counts["customer_orders"] = cur.rowcount

            # 3. Purge checkout intents
            cur.execute("DELETE FROM orchestration.checkout_intent WHERE session_id LIKE 'session_loadtest_%'")
            counts["checkout_intents"] = cur.rowcount

            # 4. Purge experience sessions
            cur.execute("DELETE FROM orchestration.experience_session WHERE session_id LIKE 'session_loadtest_%'")
            counts["experience_sessions"] = cur.rowcount

            # 5. Purge occasion memories
            cur.execute("DELETE FROM crm.customer_occasion_memory WHERE session_id LIKE 'session_loadtest_%'")
            counts["occasion_memories"] = cur.rowcount

    return counts

if __name__ == "__main__":
    print("=== AEA POST-LOAD TEST DATA PURGE ENGINE ===")
    try:
        results = purge_load_test_data(DSN)
        print("Purge completed successfully:")
        for table, count in results.items():
            print(f"  - {table}: {count} records purged")
    except Exception as e:
        print(f"Error purging load test data: {e}")
        sys.exit(1)
