#!/usr/bin/env python3
"""Unit tests for the #329 platform/edge Python lock gate."""

from __future__ import annotations

import re
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CI = ROOT / ".gitlab-ci.yml"

sys.path.insert(0, str(ROOT / "scripts"))
from check_python_locks import ci_job_errors, consumer_errors, job_block  # noqa: E402
from compile_python_locks import (  # noqa: E402
    HEADER,
    INPUTS,
    canonicalize_name,
    check_locks,
    lock_path_for,
    render_lock,
)


class PythonLockGateTests(unittest.TestCase):
    def test_human_authored_inputs_retained(self) -> None:
        self.assertEqual(
            [path.relative_to(ROOT).as_posix() for path in INPUTS],
            ["platform/requirements.txt", "edge/requirements.txt"],
        )
        for requirements in INPUTS:
            text = requirements.read_text(encoding="utf-8")
            self.assertTrue(text.strip(), requirements)
            self.assertNotIn("Generated by scripts/compile_python_locks.py", text)
            self.assertRegex(text, r"[><=]")

    def test_lock_render_is_deterministic(self) -> None:
        first = render_lock(INPUTS[0], [("psycopg", "3.2.10"), ("confluent-kafka", "2.12.1")])
        second = render_lock(INPUTS[0], [("psycopg", "3.2.10"), ("confluent-kafka", "2.12.1")])
        self.assertEqual(first, second)
        self.assertTrue(first.startswith(HEADER))
        self.assertIn("# Input: platform/requirements.txt", first)
        self.assertIn("confluent-kafka==2.12.1", first)
        self.assertNotRegex(first, r"20\d\d-\d\d-\d\d")

    def test_canonicalize_name(self) -> None:
        self.assertEqual(canonicalize_name("psycopg_binary"), "psycopg-binary")
        self.assertEqual(canonicalize_name("Confluent.Kafka"), "confluent-kafka")

    def test_stale_lock_fails_check(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            req = Path(tmp) / "requirements.txt"
            lock = Path(tmp) / "requirements.lock"
            req.write_text("uvicorn>=0.30,<1\n", encoding="utf-8")
            lock.write_text(
                HEADER + "\n# Input: requirements.txt\n\nuvicorn==0.0.0\n",
                encoding="utf-8",
            )
            errors = check_locks((req,))
            self.assertTrue(errors)
            self.assertTrue(any("does not satisfy" in error for error in errors))

    def test_specifier_matches_input_ranges(self) -> None:
        from compile_python_locks import specifier_matches

        self.assertTrue(specifier_matches("3.3.4", ">=3.2,<4"))
        self.assertTrue(specifier_matches("2.15.0", ">=2.6,<3"))
        self.assertTrue(specifier_matches("0.52.4", ">=0.30,<1"))
        self.assertFalse(specifier_matches("4.0.0", ">=3.2,<4"))
        self.assertFalse(specifier_matches("0.0.0", ">=0.30,<1"))

    def test_ci_job_is_required(self) -> None:
        block = job_block("python-lock")
        self.assertIn("python:3.12", block)
        self.assertNotIn("allow_failure:", block)
        self.assertNotIn("|| true", block)
        self.assertIn("scripts/check_python_locks.py", block)
        self.assertIn("scripts/test_python_locks.py", block)
        self.assertIn("scripts/compile_python_locks.py --check", block)
        self.assertIn("-c platform/requirements.lock", block)
        self.assertIn("-c edge/requirements.lock", block)
        self.assertNotIn("pip-audit", block)
        self.assertEqual(ci_job_errors(), [])

    def test_header_comment_calls_python_lock_blocking(self) -> None:
        header = "\n".join(CI.read_text(encoding="utf-8").splitlines()[:10])
        self.assertIn("python-lock (blocking, #329)", header)
        self.assertNotIn("python-lock (advisory)", header)
        self.assertIn("bandit (blocking, #328)", header)

    def test_consumers_use_locks(self) -> None:
        self.assertEqual(consumer_errors(), [])
        integration = job_block("platform-foundation-integration")
        self.assertIn("-c platform/requirements.lock", integration)
        self.assertNotRegex(integration, r"pip install -r platform/requirements\.txt\s*$")

    def test_committed_locks_exist_and_name_inputs(self) -> None:
        for requirements in INPUTS:
            lock = lock_path_for(requirements)
            self.assertTrue(lock.is_file(), lock)
            text = lock.read_text(encoding="utf-8")
            self.assertTrue(text.startswith(HEADER))
            self.assertIn(f"# Input: {requirements.relative_to(ROOT).as_posix()}", text)
            self.assertTrue(re.search(r"^[a-z0-9.-]+==[0-9].*$", text, re.M), text)


if __name__ == "__main__":
    unittest.main()
